name: ProserusPipeline

on: 
  push:
    branches: [main]

jobs: 
  proserusTest: 
    name: Proserus
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Install Dependencies
        run: |
          echo "Running installing dependencies..."
          yarn install
      - name: Run Tests
        run: |
          echo "Running tests..."
          yarn test
        env: 
          CI: true
